jobs:
  checkov:
    machine: true
    steps:
      - checkout

      - run:
          shell: /bin/bash 
          command: docker run --rm -w /src -v $(pwd):/src bridgecrew/checkov -d aws -o json | tee checkov-output.json
          allow_failure: true

      - store_artifacts:
          path: checkov-output.json
          destination: checkov-artifact
          when: always

  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is a test step"

  integration:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    machine: true
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  terraform:
    jobs:
      - checkov
      - test:
          requires:
            - checkov 
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
